import { formatCurrency, formatDateLong, formatPeriod } from '@/lib/formatters'
import { StatusBadge } from '@/components/ui/badge'

export type PayslipSheet = {
  employee: {
    employee_code: string
    full_name: string
    position: string | null
    department: string | null
  }
  payroll: {
    period: string
    base_salary: number
    allowance: number
    bonus: number
    deduction: number
    net_salary: number
    status: string
    published_at: string | null
  }
}

/** PRD section 51: formal, clean, print friendly. */
export function PayslipSheet({ sheet }: { sheet: PayslipSheet }) {
  const [year, month] = sheet.payroll.period.split('-')
  const earnings = [
    { label: 'Base Salary', value: sheet.payroll.base_salary },
    { label: 'Allowance', value: sheet.payroll.allowance },
    { label: 'Bonus', value: sheet.payroll.bonus },
  ]

  return (
    <div className="rounded-lg border border-line bg-surface">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-line px-6 py-5">
        <div>
          <p className="text-[11px] uppercase tracking-wide text-muted">PT Sentra Karya Digital</p>
          <h2 className="mt-0.5 text-lg font-semibold text-ink">Slip Gaji</h2>
        </div>
        <div className="text-right">
          <p className="text-[13px] font-medium text-ink">
            {formatPeriod(Number(month), Number(year))}
          </p>
          {sheet.payroll.published_at && (
            <p className="mt-0.5 text-xs text-muted">Published {formatDateLong(sheet.payroll.published_at)}</p>
          )}
        </div>
      </header>

      <div className="grid gap-x-8 gap-y-4 border-b border-line px-6 py-5 sm:grid-cols-2">
        <div>
          <p className="text-[13px] text-muted">Employee Name</p>
          <p className="text-[13px] font-medium text-ink">{sheet.employee.full_name}</p>
        </div>
        <div>
          <p className="text-[13px] text-muted">Employee ID</p>
          <p className="text-[13px] font-medium text-ink tabular-nums">{sheet.employee.employee_code}</p>
        </div>
        <div>
          <p className="text-[13px] text-muted">Department</p>
          <p className="text-[13px] font-medium text-ink">{sheet.employee.department ?? '-'}</p>
        </div>
        <div>
          <p className="text-[13px] text-muted">Position</p>
          <p className="text-[13px] font-medium text-ink">{sheet.employee.position ?? '-'}</p>
        </div>
      </div>

      <div className="grid gap-8 px-6 py-5 sm:grid-cols-2">
        <div>
          <h3 className="text-[12px] font-medium uppercase tracking-wide text-muted">Earnings</h3>
          <dl className="mt-3 space-y-2">
            {earnings.map((item) => (
              <div key={item.label} className="flex items-center justify-between gap-4">
                <dt className="text-[13px] text-ink">{item.label}</dt>
                <dd className="text-[13px] font-medium tabular-nums text-ink">{formatCurrency(item.value)}</dd>
              </div>
            ))}
          </dl>
        </div>

        <div>
          <h3 className="text-[12px] font-medium uppercase tracking-wide text-muted">Deductions</h3>
          <dl className="mt-3 space-y-2">
            <div className="flex items-center justify-between gap-4">
              <dt className="text-[13px] text-ink">Deduction</dt>
              <dd className="text-[13px] font-medium tabular-nums text-ink">
                {formatCurrency(sheet.payroll.deduction)}
              </dd>
            </div>
          </dl>
        </div>
      </div>

      <footer className="flex items-center justify-between gap-4 border-t border-line px-6 py-4">
        <div className="flex items-center gap-2">
          <span className="text-[13px] font-medium text-muted">Status</span>
          <StatusBadge value={sheet.payroll.status} />
        </div>
        <div className="text-right">
          <p className="text-[12px] uppercase tracking-wide text-muted">Net Salary</p>
          <p className="text-xl font-semibold tabular-nums text-ink">{formatCurrency(sheet.payroll.net_salary)}</p>
        </div>
      </footer>

      <p className="px-6 pb-5 text-[11px] text-muted">
        This document is generated by the HRIS and does not require a signature.
      </p>
    </div>
  )
}